apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: joshuamumo/auth  # Replace with your actual image
          env:
            - name: MONGO_URL
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:  # Fixed indentation here
                  name: resend-api-key
                  key: RESEND_API_KEY
      # Uncomment and configure imagePullSecrets if needed
      # imagePullSecrets:
      #   - name: tckt
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
